rule-engine.rabbitmq.enabled=true
rule-engine.sensor-event.queue=insighton.engine.sensor-events
rule-engine.sensor-event.exchange=insighton.core.telemetry.exchange
rule-engine.sensor-event.routing-key=#
rule-engine.prototype.test-controller.enabled=true

rule-engine.telemetry-routing.enabled=false
rule-engine.telemetry-routing.exchange=insighton.core.telemetry.exchange
rule-engine.telemetry-routing.queue-prefix=insighton.ruleengine.telemetry.queue.
rule-engine.telemetry-routing.hash-header=locationId
rule-engine.heartbeat.enabled=false
rule-engine.heartbeat.refresh-interval=5s
rule-engine.heartbeat.ttl=15s
