spring.application.name=insighton-ruleengine
server.port=8080
management.endpoints.web.exposure.include=health
service-url.core=http://insighton-core
spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.repositories.enabled=false
rule-engine.flow-cache.type=${RULE_ENGINE_FLOW_CACHE_TYPE:redis}


