# Dev-only settings. Common settings are in application.properties.
spring.config.import=classpath:config/dev/db.properties, classpath:config/dev/rabbitmq.properties, classpath:config/dev/redis.properties, classpath:config/dev/rule-engine.properties, classpath:config/dev/zipkin.properties, classpath:config/dev/telemetry-routing.properties
service-url.core=http://localhost:8100

logging.level.root=INFO
logging.level.com.nhnacademy.insightonruleengine=INFO
