# Dev-only settings. Common settings are in application.properties.
spring.config.import=classpath:config/dev/actuator.properties, classpath:config/dev/db.properties, classpath:config/dev/redis.properties, classpath:config/dev/rabbitmq.properties, classpath:config/dev/rule-engine.properties

spring.cloud.config.enabled=false
eureka.client.enabled=false
