management.zipkin.tracing.endpoint=http://insighton-zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
