spring.datasource.url=jdbc:postgresql://${DB_HOST}:8000/aiot3-team3-project?currentSchema=engine
spring.datasource.username=aiot3-team3
spring.datasource.password=${DB_PASSWORD}
spring.datasource.dbcp2.min-idle=50
spring.datasource.dbcp2.max-idle=50
spring.datasource.dbcp2.max-total=50
spring.datasource.dbcp2.initial-size=50

spring.datasource.dbcp2.test-on-borrow=true

spring.datasource.dbcp2.validation-query=select 1;