rule-engine.telemetry-routing.enabled=${TELEMETRY_ROUTING_ENABLED:true}
rule-engine.telemetry-routing.exchange=insighton.core.telemetry.exchange-v2
rule-engine.telemetry-routing.hash-header=${TELEMETRY_HASH_HEADER:locationId}
