package com.nhnacademy.insightonruleengine.flow.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.FileSystemResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
class ActionFanOutMigrationTest {

    private static final Path MIGRATION_PATH = Path.of(
            "project-docs",
            "engine-current-baseline-2026-08-31",
            "db-migrations",
            "2026-09-01-action-fan-out.sql"
    ).toAbsolutePath().normalize();

    @Container
    private static final PostgreSQLContainer<?> POSTGRESQL =
            new PostgreSQLContainer<>("postgres:16-alpine");

    @Test
    @DisplayName("Action fan-out 수동 migration은 기존 Link 제약을 안전하게 교체한다")
    void migratesLegacySourcePortConstraint() throws SQLException {
        assertTrue(Files.isRegularFile(MIGRATION_PATH), "migration SQL 파일이 저장소에 있어야 한다");

        try (Connection connection = POSTGRESQL.createConnection("")) {
            createLegacyLinksTable(connection);

            ScriptUtils.executeSqlScript(connection, new FileSystemResource(MIGRATION_PATH));

            assertEquals(
                    List.of("uk_links_flow_source_port_target"),
                    findLinkUniqueConstraintNames(connection)
            );

            insertLink(connection, 1L, 10L, "out", 20L, "in");
            insertLink(connection, 1L, 10L, "out", 21L, "in");
            assertEquals(2, countLinks(connection));

            SQLException duplicateException = assertThrows(
                    SQLException.class,
                    () -> insertLink(connection, 1L, 10L, "out", 20L, "in")
            );
            assertEquals("23505", duplicateException.getSQLState());
        }
    }

    private void createLegacyLinksTable(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("create schema engine");
            statement.execute("""
                    create table engine.links (
                        link_id bigint generated by default as identity primary key,
                        flow_id bigint not null,
                        source_node_id bigint not null,
                        source_port varchar(50) not null,
                        target_node_id bigint not null,
                        target_port varchar(50) not null
                    )
                    """);
            statement.execute("""
                    alter table engine.links
                        add constraint uk_links_flow_source_port
                            unique (flow_id, source_node_id, source_port)
                    """);
        }
    }

    private List<String> findLinkUniqueConstraintNames(Connection connection) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select conname
                from pg_constraint
                where conrelid = 'engine.links'::regclass
                  and contype = 'u'
                order by conname
                """)) {
            try (ResultSet resultSet = statement.executeQuery()) {
                List<String> constraintNames = new ArrayList<>();
                while (resultSet.next()) {
                    constraintNames.add(resultSet.getString("conname"));
                }
                return List.copyOf(constraintNames);
            }
        }
    }

    private void insertLink(
            Connection connection,
            long flowId,
            long sourceNodeId,
            String sourcePort,
            long targetNodeId,
            String targetPort
    ) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into engine.links (
                    flow_id, source_node_id, source_port, target_node_id, target_port
                ) values (?, ?, ?, ?, ?)
                """)) {
            statement.setLong(1, flowId);
            statement.setLong(2, sourceNodeId);
            statement.setString(3, sourcePort);
            statement.setLong(4, targetNodeId);
            statement.setString(5, targetPort);
            statement.executeUpdate();
        }
    }

    private int countLinks(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("select count(*) from engine.links")) {
            resultSet.next();
            return resultSet.getInt(1);
        }
    }
}
