package com.nhnacademy.insightonruleengine.flow.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.FileSystemResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
class ExternalNotificationCleanupMigrationTest {

    private static final Path MIGRATION_PATH = Path.of(
            "project-docs",
            "engine-current-baseline-2026-08-31",
            "db-migrations",
            "2026-09-03-remove-external-notification-nodes.sql"
    ).toAbsolutePath().normalize();

    @Container
    private static final PostgreSQLContainer<?> POSTGRESQL =
            new PostgreSQLContainer<>("postgres:16-alpine");

    @Test
    @DisplayName("EXTERNAL_NOTIFICATION 정리 migration은 해당 Node와 연결 Link만 지우고 나머지는 남긴다")
    void removesExternalNotificationNodesAndTheirLinks() throws SQLException {
        assertTrue(Files.isRegularFile(MIGRATION_PATH), "migration SQL 파일이 저장소에 있어야 한다");

        try (Connection connection = POSTGRESQL.createConnection("")) {
            createFlowGraphTables(connection);

            // flow 1: SENSOR -> THRESHOLD -> (true) ALERT, (false) EXTERNAL_NOTIFICATION
            insertNode(connection, 1L, 1L, "SENSOR");
            insertNode(connection, 2L, 1L, "THRESHOLD");
            insertNode(connection, 3L, 1L, "ALERT");
            insertNode(connection, 4L, 1L, "EXTERNAL_NOTIFICATION");
            insertLink(connection, 1L, 1L, 1L, "out", 2L, "in");
            insertLink(connection, 2L, 1L, 2L, "true", 3L, "in");
            insertLink(connection, 3L, 1L, 2L, "false", 4L, "in");

            // flow 2: 영향을 받지 않아야 하는 정상 Flow
            insertNode(connection, 5L, 2L, "SENSOR");
            insertNode(connection, 6L, 2L, "ALERT");
            insertLink(connection, 4L, 2L, 5L, "out", 6L, "in");

            ScriptUtils.executeSqlScript(connection, new FileSystemResource(MIGRATION_PATH));

            assertEquals(
                    0,
                    countNodesOfType(connection, "EXTERNAL_NOTIFICATION"),
                    "삭제된 NodeType 행이 남아 있으면 안 된다"
            );
            assertEquals(List.of(1L, 2L, 3L, 5L, 6L), findNodeIds(connection));
            assertEquals(List.of(1L, 2L, 4L), findLinkIds(connection));
        }
    }

    private void createFlowGraphTables(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("create schema engine");
            statement.execute("""
                    create table engine.nodes (
                        node_id bigint generated by default as identity primary key,
                        flow_id bigint not null,
                        node_type varchar(50) not null,
                        configuration jsonb not null
                    )
                    """);
            statement.execute("""
                    create table engine.links (
                        link_id bigint generated by default as identity primary key,
                        flow_id bigint not null,
                        source_node_id bigint not null,
                        source_port varchar(50) not null,
                        target_node_id bigint not null,
                        target_port varchar(50) not null
                    )
                    """);
        }
    }

    private void insertNode(
            Connection connection,
            long nodeId,
            long flowId,
            String nodeType
    ) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into engine.nodes (node_id, flow_id, node_type, configuration)
                values (?, ?, ?, '{}'::jsonb)
                """)) {
            statement.setLong(1, nodeId);
            statement.setLong(2, flowId);
            statement.setString(3, nodeType);
            statement.executeUpdate();
        }
    }

    private void insertLink(
            Connection connection,
            long linkId,
            long flowId,
            long sourceNodeId,
            String sourcePort,
            long targetNodeId,
            String targetPort
    ) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into engine.links (
                    link_id, flow_id, source_node_id, source_port, target_node_id, target_port
                ) values (?, ?, ?, ?, ?, ?)
                """)) {
            statement.setLong(1, linkId);
            statement.setLong(2, flowId);
            statement.setLong(3, sourceNodeId);
            statement.setString(4, sourcePort);
            statement.setLong(5, targetNodeId);
            statement.setString(6, targetPort);
            statement.executeUpdate();
        }
    }

    private int countNodesOfType(Connection connection, String nodeType) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "select count(*) from engine.nodes where node_type = ?")) {
            statement.setString(1, nodeType);
            try (ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getInt(1);
            }
        }
    }

    private List<Long> findNodeIds(Connection connection) throws SQLException {
        return findIds(connection, "select node_id from engine.nodes order by node_id", "node_id");
    }

    private List<Long> findLinkIds(Connection connection) throws SQLException {
        return findIds(connection, "select link_id from engine.links order by link_id", "link_id");
    }

    private List<Long> findIds(Connection connection, String sql, String column) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {
            List<Long> ids = new ArrayList<>();
            while (resultSet.next()) {
                ids.add(resultSet.getLong(column));
            }
            return List.copyOf(ids);
        }
    }
}
