package com.nhnacademy.insightonruleengine.flow.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.FileSystemResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
class FlowNamePartialUniqueMigrationTest {

    private static final Path MIGRATION_PATH = Path.of(
            "project-docs",
            "engine-current-baseline-2026-08-31",
            "db-migrations",
            "2026-09-03-flow-name-partial-unique.sql"
    ).toAbsolutePath().normalize();

    @Container
    private static final PostgreSQLContainer<?> POSTGRESQL =
            new PostgreSQLContainer<>("postgres:16-alpine");

    @Test
    @DisplayName("Flow 이름 부분 유니크 인덱스 migration은 ARCHIVED를 제외하고 유니크를 유지한다")
    void migratesToPartialUniqueIndexExcludingArchived() throws SQLException {
        assertTrue(Files.isRegularFile(MIGRATION_PATH), "migration SQL 파일이 저장소에 있어야 한다");

        try (Connection connection = POSTGRESQL.createConnection("")) {
            createLegacyFlowsTable(connection);
            insertFlow(connection, 1L, 1L, "[AI] co2 예방 자동화", "ACTIVE");

            ScriptUtils.executeSqlScript(connection, new FileSystemResource(MIGRATION_PATH));

            assertEquals(List.of(), findUniqueConstraintNames(connection));
            assertEquals(List.of("uk_flows_group_location_name"), findPartialUniqueIndexNames(connection));

            // 기존 행을 archive로 바꾸면 같은 이름의 새 행을 만들 수 있어야 한다(migration의 목적).
            archiveFlow(connection, 1L, 1L, "[AI] co2 예방 자동화");
            insertFlow(connection, 1L, 1L, "[AI] co2 예방 자동화", "INACTIVE");
            assertEquals(2, countFlows(connection));

            // ARCHIVED가 아닌 행끼리는 여전히 같은 이름을 가질 수 없어야 한다.
            SQLException duplicateException = assertThrows(
                    SQLException.class,
                    () -> insertFlow(connection, 1L, 1L, "[AI] co2 예방 자동화", "INACTIVE")
            );
            assertEquals("23505", duplicateException.getSQLState());
        }
    }

    private void createLegacyFlowsTable(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("create schema engine");
            statement.execute("""
                    create table engine.flows (
                        flow_id bigint generated by default as identity primary key,
                        group_id bigint not null,
                        location_id bigint not null,
                        name varchar(100) not null,
                        status varchar(20) not null
                    )
                    """);
            statement.execute("""
                    alter table engine.flows
                        add constraint uk_flows_group_location_name
                            unique (group_id, location_id, name)
                    """);
        }
    }

    private List<String> findUniqueConstraintNames(Connection connection) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select conname
                from pg_constraint
                where conrelid = 'engine.flows'::regclass
                  and contype = 'u'
                order by conname
                """)) {
            try (ResultSet resultSet = statement.executeQuery()) {
                List<String> names = new ArrayList<>();
                while (resultSet.next()) {
                    names.add(resultSet.getString("conname"));
                }
                return List.copyOf(names);
            }
        }
    }

    // 부분 인덱스만 찾는다. flows_pkey도 "CREATE UNIQUE INDEX ..."로 시작해 이름만으로는
    // 구분이 안 되므로, WHERE 절이 있는지로 부분 인덱스 여부를 가른다.
    private List<String> findPartialUniqueIndexNames(Connection connection) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                select indexname
                from pg_indexes
                where schemaname = 'engine'
                  and tablename = 'flows'
                  and indexdef ilike 'CREATE UNIQUE INDEX%'
                  and indexdef ilike '%WHERE%'
                order by indexname
                """)) {
            try (ResultSet resultSet = statement.executeQuery()) {
                List<String> names = new ArrayList<>();
                while (resultSet.next()) {
                    names.add(resultSet.getString("indexname"));
                }
                return List.copyOf(names);
            }
        }
    }

    private void insertFlow(
            Connection connection,
            long groupId,
            long locationId,
            String name,
            String status
    ) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into engine.flows (group_id, location_id, name, status)
                values (?, ?, ?, ?)
                """)) {
            statement.setLong(1, groupId);
            statement.setLong(2, locationId);
            statement.setString(3, name);
            statement.setString(4, status);
            statement.executeUpdate();
        }
    }

    private void archiveFlow(Connection connection, long groupId, long locationId, String name) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                update engine.flows
                set status = 'ARCHIVED'
                where group_id = ? and location_id = ? and name = ?
                """)) {
            statement.setLong(1, groupId);
            statement.setLong(2, locationId);
            statement.setString(3, name);
            statement.executeUpdate();
        }
    }

    private int countFlows(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("select count(*) from engine.flows")) {
            resultSet.next();
            return resultSet.getInt(1);
        }
    }
}
