package com.nhnacademy.insightonruleengine.flow.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.FileSystemResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
class ProductionFlowResetMigrationTest {

    private static final Path MIGRATION_PATH = Path.of(
            "project-docs",
            "engine-current-baseline-2026-08-31",
            "db-migrations",
            "2026-09-03-reset-flows-and-finalize-event-gate.sql"
    ).toAbsolutePath().normalize();

    @Container
    private static final PostgreSQLContainer<?> POSTGRESQL =
            new PostgreSQLContainer<>("postgres:16-alpine");

    @Test
    @DisplayName("운영 Flow 초기화 SQL은 데이터를 비우고 최종 Node·Link·이름 제약을 적용한다")
    void resetsFlowDataAndAppliesFinalConstraints() throws SQLException {
        assertTrue(Files.isRegularFile(MIGRATION_PATH), "운영 전환 SQL 파일이 저장소에 있어야 한다");

        try (Connection connection = POSTGRESQL.createConnection("")) {
            createLegacySchema(connection);
            insertLegacyData(connection);

            ScriptUtils.executeSqlScript(connection, new FileSystemResource(MIGRATION_PATH));

            assertEquals(0, countRows(connection, "engine.links"));
            assertEquals(0, countRows(connection, "engine.nodes"));
            assertEquals(0, countRows(connection, "engine.flows"));

            long flowId = insertFlow(connection, 1L, 10L, "최종 Flow", "ACTIVE");
            assertEquals(2L, flowId, "Redis 잔존 키와 충돌하지 않도록 identity를 재사용하지 않아야 한다");
            long gateId = insertNode(connection, flowId, "EVENT_GATE");
            long firstAlertId = insertNode(connection, flowId, "ALERT");
            long secondAlertId = insertNode(connection, flowId, "ALERT");

            assertCheckViolation(connection, flowId, "TIMER");
            assertCheckViolation(connection, flowId, "EXTERNAL_NOTIFICATION");

            insertLink(connection, flowId, gateId, "true", firstAlertId, "in");
            insertLink(connection, flowId, gateId, "true", secondAlertId, "in");
            SQLException duplicateLink = assertThrows(
                    SQLException.class,
                    () -> insertLink(connection, flowId, gateId, "true", firstAlertId, "in")
            );
            assertEquals("23505", duplicateLink.getSQLState());

            insertFlow(connection, 1L, 10L, "최종 Flow", "ARCHIVED");
            SQLException duplicateActiveFlow = assertThrows(
                    SQLException.class,
                    () -> insertFlow(connection, 1L, 10L, "최종 Flow", "INACTIVE")
            );
            assertEquals("23505", duplicateActiveFlow.getSQLState());
        }
    }

    private void createLegacySchema(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("create schema engine");
            statement.execute("""
                    create table engine.flows (
                        flow_id bigint generated by default as identity primary key,
                        created_at timestamp(6) with time zone not null,
                        description text,
                        group_id bigint not null,
                        location_id bigint not null,
                        name varchar(100) not null,
                        status varchar(20) not null,
                        constraint flows_status_check
                            check (status in ('ACTIVE', 'INACTIVE', 'ARCHIVED', 'ERROR')),
                        constraint uk_flows_group_location_name
                            unique (group_id, location_id, name)
                    )
                    """);
            statement.execute("""
                    create table engine.nodes (
                        node_id bigint generated by default as identity primary key,
                        configuration jsonb not null,
                        flow_id bigint not null,
                        node_type varchar(50) not null,
                        constraint nodes_node_type_check check (node_type in (
                            'SENSOR', 'LOCATION', 'SCHEDULE', 'THRESHOLD', 'TIME_WINDOW',
                            'TIMER', 'ACTUATOR_CONTROL', 'ALERT', 'EXTERNAL_NOTIFICATION'
                        ))
                    )
                    """);
            statement.execute("""
                    create table engine.links (
                        link_id bigint generated by default as identity primary key,
                        flow_id bigint not null,
                        source_node_id bigint not null,
                        source_port varchar(50) not null,
                        target_node_id bigint not null,
                        target_port varchar(50) not null,
                        constraint uk_links_flow_source_port
                            unique (flow_id, source_node_id, source_port)
                    )
                    """);
        }
    }

    private void insertLegacyData(Connection connection) throws SQLException {
        long flowId = insertFlow(connection, 3L, 30L, "기존 Flow", "ACTIVE");
        long timerId = insertNode(connection, flowId, "TIMER");
        long externalNotificationId = insertNode(connection, flowId, "EXTERNAL_NOTIFICATION");
        insertLink(connection, flowId, timerId, "true", externalNotificationId, "in");
    }

    private long insertFlow(Connection connection, long groupId, long locationId, String name, String status)
            throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into engine.flows (created_at, group_id, location_id, name, status)
                values (current_timestamp, ?, ?, ?, ?)
                returning flow_id
                """)) {
            statement.setLong(1, groupId);
            statement.setLong(2, locationId);
            statement.setString(3, name);
            statement.setString(4, status);
            try (ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getLong(1);
            }
        }
    }

    private long insertNode(Connection connection, long flowId, String nodeType) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into engine.nodes (flow_id, node_type, configuration)
                values (?, ?, '{}'::jsonb)
                returning node_id
                """)) {
            statement.setLong(1, flowId);
            statement.setString(2, nodeType);
            try (ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getLong(1);
            }
        }
    }

    private void assertCheckViolation(Connection connection, long flowId, String nodeType) {
        SQLException exception = assertThrows(SQLException.class, () -> insertNode(connection, flowId, nodeType));
        assertEquals("23514", exception.getSQLState());
    }

    private void insertLink(
            Connection connection,
            long flowId,
            long sourceNodeId,
            String sourcePort,
            long targetNodeId,
            String targetPort
    ) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                insert into engine.links (flow_id, source_node_id, source_port, target_node_id, target_port)
                values (?, ?, ?, ?, ?)
                """)) {
            statement.setLong(1, flowId);
            statement.setLong(2, sourceNodeId);
            statement.setString(3, sourcePort);
            statement.setLong(4, targetNodeId);
            statement.setString(5, targetPort);
            statement.executeUpdate();
        }
    }

    private int countRows(Connection connection, String tableName) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("select count(*) from " + tableName)) {
            resultSet.next();
            return resultSet.getInt(1);
        }
    }
}
